/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des catégories */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                    search?: components["parameters"]["SearchParam"];
                    isActive?: components["parameters"]["IsActiveParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedMeta"] & {
                            data?: components["schemas"]["Category"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Détail d'une catégorie */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Créer ou modifier une catégorie
         * @description 201 si création, 200 si mise à jour
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryPayload"];
                };
            };
            responses: {
                /** @description Modifié */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                /** @description Créé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /** Supprimer une catégorie (soft delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supprimé */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des produits */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                    search?: components["parameters"]["SearchParam"];
                    isActive?: components["parameters"]["IsActiveParam"];
                    categoryId?: string;
                    parentId?: string;
                    /** @description Retourner uniquement les produits racines (sans parent) */
                    rootOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedMeta"] & {
                            data?: components["schemas"]["ProductSummary"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Détail d'un produit avec ses prix actifs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Créer ou modifier un produit
         * @description 201 si création, 200 si mise à jour
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductPayload"];
                };
            };
            responses: {
                /** @description Modifié */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                /** @description Créé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /** Supprimer un produit (soft delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supprimé */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Dérivés d'un produit */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ProductSummary"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Stock actuel d'un produit (solde calculé) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductStockSummary"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Historique des prix d'un produit */
        get: {
            parameters: {
                query?: {
                    activeOnly?: boolean;
                };
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ProductPrice"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Créer ou modifier un prix
         * @description L'id du produit est dans le payload (`productId`).
         *     201 si création, 200 si mise à jour.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductPricePayload"];
                };
            };
            responses: {
                /** @description Modifié */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductPrice"];
                    };
                };
                /** @description Créé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductPrice"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /** Supprimer un prix (soft delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supprimé */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packaging": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des conditionnements */
        get: {
            parameters: {
                query?: {
                    isActive?: components["parameters"]["IsActiveParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Packaging"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packaging/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Créer ou modifier un conditionnement
         * @description 201 si création, 200 si mise à jour
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PackagingPayload"];
                };
            };
            responses: {
                /** @description Modifié */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Packaging"];
                    };
                };
                /** @description Créé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Packaging"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /** Supprimer un conditionnement (soft delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supprimé */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des fournisseurs */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                    search?: components["parameters"]["SearchParam"];
                    isActive?: components["parameters"]["IsActiveParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedMeta"] & {
                            data?: components["schemas"]["Supplier"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Détail d'un fournisseur */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Supplier"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Créer ou modifier un fournisseur
         * @description 201 si création, 200 si mise à jour
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SupplierPayload"];
                };
            };
            responses: {
                /** @description Modifié */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Supplier"];
                    };
                };
                /** @description Créé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Supplier"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /** Supprimer un fournisseur (soft delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supprimé */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mouvements de stock */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                    productId?: string;
                    supplierId?: string;
                    type?: "entry" | "exit";
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedMeta"] & {
                            data?: components["schemas"]["StockMovement"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Solde de stock par produit (vue agrégée) */
        get: {
            parameters: {
                query?: {
                    categoryId?: string;
                    lowStock?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ProductStockSummary"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Détail d'un mouvement de stock */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StockMovement"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Enregistrer ou corriger un mouvement de stock
         * @description 201 si création, 200 si correction.
         *     Les mouvements générés par une vente ou une transformation ne sont pas modifiables ici.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StockMovementPayload"];
                };
            };
            responses: {
                /** @description Modifié */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StockMovement"];
                    };
                };
                /** @description Créé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StockMovement"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /** Annuler un mouvement (soft delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Annulé */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transformations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des transformations */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                    productId?: string;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedMeta"] & {
                            data?: components["schemas"]["Transformation"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transformations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Détail d'une transformation avec inputs et outputs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transformation"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Créer ou modifier une transformation
         * @description 201 → génère automatiquement les mouvements de stock (sorties inputs, entrées outputs).
         *     200 → recalcule les mouvements de stock associés.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransformationPayload"];
                };
            };
            responses: {
                /** @description Modifié */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transformation"];
                    };
                };
                /** @description Créé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transformation"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des ventes */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    limit?: components["parameters"]["LimitParam"];
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedMeta"] & {
                            data?: components["schemas"]["SaleSummary"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Détail d'une vente avec toutes ses lignes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sale"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Créer ou modifier une vente
         * @description 201 → génère automatiquement les sorties de stock.
         *     200 → recalcule le stock si les lignes ont changé.
         *     Le `totalAmount` est calculé côté serveur.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SalePayload"];
                };
            };
            responses: {
                /** @description Modifié */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sale"];
                    };
                };
                /** @description Créé */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sale"];
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /** Annuler une vente (soft delete + réintégration stock) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Annulé */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaginatedMeta: {
            meta?: {
                total?: number;
                page?: number;
                limit?: number;
                totalPages?: number;
            };
        };
        ErrorResponse: {
            error?: {
                code?: string;
                message?: string;
            };
        };
        ValidationErrorResponse: {
            error?: {
                code?: string;
                message?: string;
                fields?: {
                    [key: string]: string;
                };
            };
        };
        Category: {
            /** Format: uuid */
            readonly id?: string;
            label?: string;
            description?: string | null;
            isActive?: boolean;
        };
        CategoryPayload: {
            label: string;
            description?: string | null;
            /** @default true */
            isActive: boolean;
        };
        Packaging: {
            /** Format: uuid */
            readonly id?: string;
            /** @example sachet */
            label?: string;
            description?: string | null;
            isActive?: boolean;
        };
        PackagingPayload: {
            label: string;
            description?: string | null;
            isActive?: boolean;
        };
        ProductSummary: {
            /** Format: uuid */
            id?: string;
            label?: string;
            category?: {
                /** Format: uuid */
                id?: string;
                label?: string;
            };
            isActive?: boolean;
            /** @description Nombre de produits dérivés (enfants) */
            readonly variantCount?: number;
            readonly currentStock?: number;
            readonly activePriceCount?: number;
        };
        Product: components["schemas"]["ProductSummary"] & {
            description?: string | null;
            parent?: {
                /** Format: uuid */
                id?: string;
                label?: string;
            } | null;
            activePrices?: components["schemas"]["ProductPrice"][];
            variants?: components["schemas"]["ProductSummary"][];
        };
        ProductPayload: {
            label: string;
            description?: string | null;
            /** Format: uuid */
            categoryId: string;
            /** Format: uuid */
            parentId?: string | null;
            /** @default true */
            isActive: boolean;
        };
        ProductPrice: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            productId?: string;
            packaging?: components["schemas"]["Packaging"];
            /** @example 4500 */
            amount?: number;
            /** @example 500 */
            weightGrams?: number;
            /** Format: date-time */
            validFrom?: string;
            /** Format: date-time */
            validTo?: string | null;
            description?: string | null;
            isActive?: boolean;
        };
        ProductPricePayload: {
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            packagingId?: string | null;
            amount: number;
            weightGrams: number;
            /** Format: date-time */
            validFrom: string;
            /** Format: date-time */
            validTo?: string | null;
            description?: string | null;
            isActive?: boolean;
        };
        Supplier: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            contact?: string | null;
            description?: string | null;
            isActive?: boolean;
        };
        SupplierPayload: {
            name: string;
            contact?: string | null;
            description?: string | null;
            isActive?: boolean;
        };
        StockMovement: {
            /** Format: uuid */
            readonly id?: string;
            /** @enum {string} */
            type?: "entry" | "exit";
            product?: {
                /** Format: uuid */
                id?: string;
                label?: string;
            };
            supplier?: {
                /** Format: uuid */
                id?: string;
                name?: string;
            } | null;
            quantity?: number;
            weightGrams?: number;
            unitPrice?: number | null;
            /** @enum {string} */
            readonly origin?: "manual" | "sale" | "transformation";
            description?: string | null;
            isActive?: boolean;
        };
        StockMovementPayload: {
            /** @enum {string} */
            type: "entry" | "exit";
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            supplierId?: string | null;
            quantity: number;
            weightGrams?: number;
            unitPrice?: number | null;
            description?: string | null;
        };
        ProductStockSummary: {
            product?: {
                /** Format: uuid */
                id?: string;
                label?: string;
            };
            totalQuantity?: number;
            totalWeightGrams?: number;
            /** Format: date-time */
            lastMovementAt?: string | null;
        };
        TransformationInput: {
            /** Format: uuid */
            readonly id?: string;
            product?: {
                /** Format: uuid */
                id?: string;
                label?: string;
            };
            quantity?: number;
            weightGrams?: number;
        };
        TransformationOutput: {
            /** Format: uuid */
            readonly id?: string;
            product?: {
                /** Format: uuid */
                id?: string;
                label?: string;
            };
            quantity?: number;
            weightGrams?: number;
            lossGrams?: number;
        };
        Transformation: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: date-time */
            transformedAt?: string;
            description?: string | null;
            inputs?: components["schemas"]["TransformationInput"][];
            outputs?: components["schemas"]["TransformationOutput"][];
            readonly totalInputWeightGrams?: number;
            readonly totalOutputWeightGrams?: number;
            readonly totalLossGrams?: number;
            readonly lossRatio?: number;
            isActive?: boolean;
        };
        TransformationPayload: {
            /** Format: date-time */
            transformedAt: string;
            description?: string | null;
            inputs: {
                /** Format: uuid */
                productId: string;
                quantity: number;
                weightGrams: number;
            }[];
            outputs: {
                /** Format: uuid */
                productId: string;
                quantity: number;
                weightGrams: number;
                /** @default 0 */
                lossGrams: number;
            }[];
        };
        SaleItem: {
            /** Format: uuid */
            readonly id?: string;
            product?: {
                /** Format: uuid */
                id?: string;
                label?: string;
            };
            price?: components["schemas"]["ProductPrice"];
            quantity?: number;
            unitPrice?: number;
            /** @description Poids total réel pour cette ligne (utilisé pour le stock) */
            totalWeightGrams?: number;
            readonly subtotal?: number;
        };
        SaleSummary: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            saleDate?: string;
            totalAmount?: number;
            readonly itemCount?: number;
            description?: string | null;
            isActive?: boolean;
        };
        Sale: components["schemas"]["SaleSummary"] & {
            items?: components["schemas"]["SaleItem"][];
        };
        SalePayload: {
            /** Format: date-time */
            saleDate: string;
            description?: string | null;
            items: {
                /** Format: uuid */
                productId: string;
                /** Format: uuid */
                productPriceId: string;
                /**
                 * @description Multiplicateur du prix.
                 *     Si omis, calculé comme totalWeightGrams / price.weightGrams.
                 */
                quantity?: number;
                /**
                 * @description Poids réel pour le déstockage.
                 *     Si omis, calculé comme quantity * price.weightGrams.
                 */
                totalWeightGrams?: number;
            }[];
        };
    };
    responses: {
        /** @description Ressource introuvable */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "La ressource demandée est introuvable"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Données invalides */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorResponse"];
            };
        };
    };
    parameters: {
        IdParam: string;
        PageParam: number;
        LimitParam: number;
        SearchParam: string;
        IsActiveParam: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
